/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.expenseitem.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.math.BigDecimal;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class ExpenseItem {

    @Id
    @NotNull(message = "ExpenseItem ID cannot be null")
    private String id;

    @Basic
    @NotNull(message = "description field in ExpenseItem must not be null")
    private String description;

    /**
     * unit amount/price
     */
    @Basic
    private int amount;

    @Basic
    @Min(value = 1, message = "A quantity must be provided in the ExpenseItem")
    private int qty;

    @Basic
    @Column(scale = 2, precision = 5)
    @NotNull(message = "vatrate field in ExpenseItem must not be null")
    private BigDecimal vatRate;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public int getQty() {
        return qty;
    }

    public void setQty(int qty) {
        this.qty = qty;
    }

    public BigDecimal getVatRate() {
        return vatRate;
    }

    public void setVatRate(BigDecimal vatRate) {
        this.vatRate = vatRate;
    }

}