/** * This file was generated by the JPA Modeler */
package fr.trendev.kiam.service.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.kiam.offering.entities.Offering;
import fr.trendev.kiam.offering.entities.OfferingType;
import fr.trendev.kiam.professional.entities.Professional;
import fr.trendev.kiam.professional.entities.Professional;
import fr.trendev.kiam.utils.Visitor;
import javax.persistence.Entity;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Service extends Offering {

    public Service(String name, int price, int duration, Professional professional) {
        super(name, price, duration, professional);
        this.cltype = OfferingType.SERVICE;
    }

    public Service() {
        this.cltype = OfferingType.SERVICE;
    }

    @Override
    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}