/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.customerdetails.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.utils.Visitor;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;

/**
 * @author jsie
 */
@Entity
@Table(name = "CUSTOMER_DETAILS")
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class CustomerDetails {

    @Id
    @NotNull(message = "CustomerDetails ID cannot be null")
    private String id;

    @Basic
    private String firstName;

    @Basic
    private String lastName;

    @Basic
    private String nickname;

    /**
     * The phone is represented by a String. At the present time, no regexp
     * validation is performed.
     */
    @Basic
    private String phone;

    /**
     * Birthdate is stored in DB as DATETIME(3). In order to avoid issues with
     * javascript/JAVA conversion on Dates before 1970 and earlier, we've
     * decided to store the DATETIME and let down the DATE only.
     */
    @Basic
    @Column(columnDefinition = "DATETIME(3)")
    @Temporal(TemporalType.TIMESTAMP)
    @Past(message = "Birthdate cannot be today or in the future...")
    private Date birthdate;

    /**
     * Should be 'F' or 'M'
     */
    @Basic
    private char sex = 'F';

    /**
     * Path on the server FS - not used at the present time
     */
    @Basic
    private String picturePath;

    @ElementCollection
    private List<String> comments = new ArrayList<>();

    public CustomerDetails(String firstName, String lastName, String nickname, String phone, Date birthdate, char sex, String picturePath) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.nickname = nickname;
        this.phone = phone;
        this.birthdate = birthdate;
        this.sex = sex;
        this.picturePath = picturePath;
    }

    public CustomerDetails() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Date getBirthdate() {
        return birthdate;
    }

    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    public char getSex() {
        return sex;
    }

    public void setSex(char sex) {
        this.sex = sex;
    }

    public String getPicturePath() {
        return picturePath;
    }

    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath;
    }

    public List<String> getComments() {
        return comments;
    }

    public void setComments(List<String> comments) {
        this.comments = comments;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}