/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.thresholdalert.entities;

import fr.trendev.comptandye.professional.entities.Professional;
import fr.trendev.comptandye.notification.entities.Notification;
import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.notification.entities.NotificationLevelEnum;
import fr.trendev.comptandye.notification.entities.NotificationType;
import fr.trendev.comptandye.utils.ThresholdAlertQualifierEnum;
import fr.trendev.comptandye.utils.visitors.Visitor;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class ThresholdAlert extends Notification {

    @Basic
    @NotNull(message = "Barcode in ThresholdAlert must not be null")
    private String barcode;

    @Basic
    @NotNull(message = "Description in ThresholdAlert must not be null")
    private String description;

    @Basic
    @NotNull(message = "brand field in Threshold must not be null")
    private String brand;

    @Basic
    @Min(value = 0,
            message = "threshold field in ThresholdAlert must not be less than 0")
    private int threshold;

    @Basic
    private int qty;

    @Basic
    @Enumerated(EnumType.STRING)
    @NotNull(message = "qualifier field in ThresholdAlert must not be null")
    private ThresholdAlertQualifierEnum qualifier;

    public ThresholdAlert() {
        super();
        this.cltype = NotificationType.THRESHOLD_ALERT;
    }

    public ThresholdAlert(NotificationLevelEnum levelRank,
            Professional professional, String barcode, String description,
            String brand, int threshold, int qty,
            ThresholdAlertQualifierEnum qualifier) {
        super(levelRank, professional);
        this.barcode = barcode;
        this.description = description;
        this.brand = brand;
        this.threshold = threshold;
        this.qty = qty;
        this.qualifier = qualifier;
        this.cltype = NotificationType.THRESHOLD_ALERT;
    }

    public String getBarcode() {
        return this.barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getBrand() {
        return this.brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public int getThreshold() {
        return this.threshold;
    }

    public void setThreshold(int threshold) {
        this.threshold = threshold;
    }

    public int getQty() {
        return this.qty;
    }

    public void setQty(int qty) {
        this.qty = qty;
    }

    public ThresholdAlertQualifierEnum getQualifier() {
        return this.qualifier;
    }

    public void setQualifier(ThresholdAlertQualifierEnum qualifier) {
        this.qualifier = qualifier;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}