/** * This file was generated by the JPA Modeler */
package fr.trendev.kiam.vatrates.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class VatRates {

    @Id
    private String countryId;

    @Basic
    private String country;

    @ElementCollection
    @Column(scale = 2, precision = 5)
    private List<BigDecimal> rates = new ArrayList<>();

    public String getCountryId() {
        return countryId;
    }

    public void setCountryId(String countryId) {
        this.countryId = countryId;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public List<BigDecimal> getRates() {
        return rates;
    }

    public void setRates(List<BigDecimal> rates) {
        this.rates = rates;
    }

}