version: 2
jobs:
  build_master:
    environment:
      IMAGE_NAME : trendev/kiam-backend
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: docker build
          command: DOCKER_BUILDKIT=1 docker build --build-arg SLACK_TOKEN1=$SLACK_TOKEN1 --build-arg SLACK_TOKEN2=$SLACK_TOKEN2 --build-arg SLACK_TOKEN3=$SLACK_TOKEN3 --build-arg NEW_ADMIN_PASSWORD=$PAYARA_ADMIN_PASSWORD_KIAM -t $IMAGE_NAME --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run:
          name: docker tag
          command: docker tag $IMAGE_NAME $IMAGE_NAME:${CIRCLE_SHA1:0:8}
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker push $IMAGE_NAME:latest
          command: docker push $IMAGE_NAME:latest
      - run:
          name: docker push $IMAGE_NAME:${CIRCLE_SHA1:0:8}
          command: docker push $IMAGE_NAME:${CIRCLE_SHA1:0:8}
  build: # generic job for other branches
    environment:
      IMAGE_NAME : trendev/kiam-backend
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: docker build
          command: DOCKER_BUILDKIT=1 docker build --build-arg SLACK_TOKEN1=$SLACK_TOKEN1 --build-arg SLACK_TOKEN2=$SLACK_TOKEN2 --build-arg SLACK_TOKEN3=$SLACK_TOKEN3 --build-arg NEW_ADMIN_PASSWORD=$PAYARA_ADMIN_PASSWORD_KIAM -t $IMAGE_NAME:$CIRCLE_BRANCH -f $CIRCLE_BRANCH.Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run:
          name : docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker push
          command: docker push $IMAGE_NAME:$CIRCLE_BRANCH
workflows:
  version: 2
  commit:
    jobs:
    - build_master:
        filters:
            branches:
              only: master
    - build:
        filters:
            branches:
              only:
                - preprod
                - preview
