/** * This file was generated by the JPA Modeler */
package fr.trendev.kiam.address.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.kiam.utils.Visitor;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Address {

    @Id
    @NotNull(message = "Address ID cannot be null")
    private String id;

    @Basic
    private String street;

    @Basic
    private String optional;

    @Basic
    private String postalCode;

    @Basic
    private String city;

    @Basic
    private String country = "France";

    public Address(String street, String optional, String postalCode, String city, String country) {
        this.street = street;
        this.optional = optional;
        this.postalCode = postalCode;
        this.city = city;
        this.country = country;
    }

    public Address() {
    }

    public Address(String street, String optional, String postalCode, String city) {
        this.street = street;
        this.optional = optional;
        this.postalCode = postalCode;
        this.city = city;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getOptional() {
        return optional;
    }

    public void setOptional(String optional) {
        this.optional = optional;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}