/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.productreference.entities;

import fr.trendev.comptandye.business.entities.Business;
import com.fasterxml.jackson.annotation.JsonInclude;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class ProductReference {

    @Column(updatable = false, nullable = false)
    @Id
    private String barcode;

    @Basic
    @NotNull(message = "description field in ProductReference must not be null")
    private String description;

    @Basic
    @NotNull(message = "brand field in ProductReference must not be null")
    private String brand;

    @OneToOne(targetEntity = Business.class)
    @NotNull(message = "business field in ProductReference must not be null")
    private Business business;

    public String getBarcode() {
        return this.barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getBrand() {
        return this.brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public Business getBusiness() {
        return this.business;
    }

    public void setBusiness(Business business) {
        this.business = business;
    }

}