/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.business.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.utils.Visitor;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Business {

    /**
     * the business designation (name)
     */
    @Id
    private String designation;

    public Business(String designation) {
        this.designation = designation;
    }

    public Business() {
    }

    public String getDesignation() {
        return this.designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}