/** * This file was generated by the JPA Modeler */
package fr.trendev.kiam.category.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.kiam.client.entities.Client;
import fr.trendev.kiam.professional.entities.Professional;
import fr.trendev.kiam.utils.Visitor;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

/**
 * @author jsie
 */
@Entity
@IdClass(CategoryPK.class)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Category {

    @Id
    @Column(name = "CATEGORY_ID")
    @NotNull(message = "Category ID cannot be null")
    private String id;

    @Basic
    private String description;

    @Basic
    private String name;

    @Id
    @ManyToOne
    @JoinColumn(name = "CATEGORY_PRO_EMAIL", referencedColumnName = "EMAIL")
    @JsonIgnore
    private Professional professional;

    @ManyToMany(mappedBy = "categories")
    @JsonIgnore
    private List<Client> clients = new LinkedList<>();

    public Category(String description, String name, Professional professional) {
        this.description = description;
        this.name = name;
        this.professional = professional;
    }

    public Category() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Professional getProfessional() {
        return professional;
    }

    public void setProfessional(Professional professional) {
        this.professional = professional;
    }

    public List<Client> getClients() {
        return clients;
    }

    public void setClients(List<Client> clients) {
        this.clients = clients;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}