/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.solditem.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.bill.entities.Bill;
import fr.trendev.comptandye.productrecord.entities.ProductRecord;
import fr.trendev.comptandye.productrecord.entities.ProductRecordType;
import fr.trendev.comptandye.utils.Visitor;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToOne;

/**
 * Record added when an item is sold and linked with an active Bill
 *
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class SoldItem extends ProductRecord {

    @OneToOne
    @JoinTable(name = "SOLD_ITEM", joinColumns = @JoinColumn(name = "ID", referencedColumnName = "ID", table = "PRODUCTRECORD"))
    private Bill bill;

    public SoldItem() {
        super();
        this.cltype = ProductRecordType.SOLD_ITEM;
    }

    public Bill getBill() {
        return bill;
    }

    public void setBill(Bill bill) {
        this.bill = bill;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}