/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.useditem.entities;

import fr.trendev.comptandye.productrecord.entities.ProductRecord;
import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.utils.ProductRecordType;
import fr.trendev.comptandye.utils.visitors.Visitor;
import javax.persistence.Entity;

/**
 * Record added when an Item is consumed during the delivery
 *
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class UsedItem extends ProductRecord {

    public UsedItem() {
        super();
        this.cltype = ProductRecordType.USED_ITEM;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}