/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.address.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.utils.visitors.Visitor;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Address {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String street;

    @Basic
    private String optional;

    @Basic
    private String postalCode;

    @Basic
    private String city;

    @Basic
    private String country = "France";

    public Address(String street, String optional, String postalCode,
            String city, String country) {
        this.street = street;
        this.optional = optional;
        this.postalCode = postalCode;
        this.city = city;
        this.country = country;
    }

    public Address() {
    }

    public Address(String street, String optional, String postalCode,
            String city) {
        this.street = street;
        this.optional = optional;
        this.postalCode = postalCode;
        this.city = city;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getOptional() {
        return this.optional;
    }

    public void setOptional(String optional) {
        this.optional = optional;
    }

    public String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}