/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.trendev.comptandye.utils.misc;

import java.io.UnsupportedEncodingException;
import java.util.Properties;
import javax.annotation.Resource;
import javax.ejb.Singleton;
import javax.ejb.Startup;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author jsie
 */
@Singleton
@Startup
public class EmailSender {

    @Resource(name = "java/mail/google-comptandye")
    Session mailSession;

    public void sendAutogeneratedPassword(String proEmail, String msg) throws MessagingException,
            UnsupportedEncodingException {
        MimeMessage message = new MimeMessage(mailSession);

        message.setSubject("Hi");
        message.setFrom(new InternetAddress("support@comptandye.fr", "Support comptandye"));
        message.setReplyTo(new InternetAddress[]{
            new InternetAddress("support@comptandye.fr", "Support comptandye")
        });
        message.setRecipient(Message.RecipientType.TO, new InternetAddress(
                proEmail, "Random Guest"));
        message.setContent("<p>" + msg + "</p>",
                "text/html; charset=utf-8");

        Transport.send(message);
    }
}
