/** * This file was generated by the JPA Modeler */
package fr.trendev.kiam.purchaseditem.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.kiam.productrecord.entities.ProductRecord;
import fr.trendev.kiam.productrecord.entities.ProductRecordType;
import fr.trendev.kiam.purchaseexpense.entities.PurchaseExpense;
import fr.trendev.kiam.utils.Visitor;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;

/**
 * Record added when an item is purchased (bought by the professional). Must be
 * associated with an Expense (Purchase).
 *
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class PurchasedItem extends ProductRecord {

    @ManyToOne
    private PurchaseExpense purchaseExpense;

    public PurchasedItem() {
        super();
        this.cltype = ProductRecordType.PURCHASED_ITEM;
    }

    public PurchaseExpense getPurchaseExpense() {
        return purchaseExpense;
    }

    public void setPurchaseExpense(PurchaseExpense purchaseExpense) {
        this.purchaseExpense = purchaseExpense;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}