/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.socialnetworkaccounts.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.utils.Visitor;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * @author jsie
 */
@Entity
@Table(name = "SOCIAL_NETWORK_ACCOUNT")
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class SocialNetworkAccounts {

    @Id
    @NotNull(message = "SocialNetworkAccounts ID cannot be null")
    private String id;

    @Basic
    private String facebook;

    @Basic
    private String twitter;

    @Basic
    private String instagram;

    @Basic
    private String pinterest;

    public SocialNetworkAccounts(String facebook, String twitter, String instagram, String pinterest) {
        this.facebook = facebook;
        this.twitter = twitter;
        this.instagram = instagram;
        this.pinterest = pinterest;
    }

    public SocialNetworkAccounts() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFacebook() {
        return facebook;
    }

    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }

    public String getTwitter() {
        return twitter;
    }

    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }

    public String getInstagram() {
        return instagram;
    }

    public void setInstagram(String instagram) {
        this.instagram = instagram;
    }

    public String getPinterest() {
        return pinterest;
    }

    public void setPinterest(String pinterest) {
        this.pinterest = pinterest;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}