/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.purchaseditem.entities;

import fr.trendev.comptandye.purchaseexpense.entities.PurchaseExpense;
import fr.trendev.comptandye.productrecord.entities.ProductRecord;
import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.productrecord.entities.ProductRecordType;
import fr.trendev.comptandye.utils.Visitor;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;

/**
 * Recored added when an item is purchased(bought by the professional) must be
 * linked to an Expense (Purchase)
 *
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class PurchasedItem extends ProductRecord {

    @ManyToOne(targetEntity = PurchaseExpense.class)
    private PurchaseExpense purchaseExpense;

    public PurchasedItem() {
        super();
        this.cltype = ProductRecordType.PURCHASED_ITEM;
    }

    public PurchaseExpense getPurchaseExpense() {
        return this.purchaseExpense;
    }

    public void setPurchaseExpense(PurchaseExpense purchaseExpense) {
        this.purchaseExpense = purchaseExpense;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}