//
// This file was generated by the JPA Modeler
//
package fr.trendev.comptandye.entity;

import java.io.Serializable;
import java.util.Date;




public class BillPK implements Serializable {

    private Long reference;

    private Date deliveyDate;

    private String professional;

    public BillPK(){
    }

    public BillPK(Long reference,Date deliveyDate,String professional){
        this.reference=reference;
        this.deliveyDate=deliveyDate;
        this.professional=professional;
    }


   public Long getReference() {
        return this.reference;
    }

    public void setReference (Long reference) {
        this.reference = reference;
    }

   public Date getDeliveyDate() {
        return this.deliveyDate;
    }

    public void setDeliveyDate (Date deliveyDate) {
        this.deliveyDate = deliveyDate;
    }

   public String getProfessional() {
        return this.professional;
    }

    public void setProfessional (String professional) {
        this.professional = professional;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {return false;}
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {return false;}
        final BillPK other = (BillPK) obj;
        if (!java.util.Objects.equals(this.getReference(), other.getReference())) {        return false;        }
        if (!java.util.Objects.equals(this.getDeliveyDate(), other.getDeliveyDate())) {        return false;        }
        if (!java.util.Objects.equals(this.getProfessional(), other.getProfessional())) {        return false;        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 29 * hash + (this.getReference() != null ? this.getReference().hashCode() : 0);
        hash = 29 * hash + (this.getDeliveyDate() != null ? this.getDeliveyDate().hashCode() : 0);
        hash = 29 * hash + (this.getProfessional() != null ? this.getProfessional().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "BillPK{" + " reference=" + reference + ", deliveyDate=" + deliveyDate + ", professional=" + professional + '}';
    }

}
