/**
 * This file was generated by the JPA Modeler
 */ 

package fr.trendev.comptandye.entity;

import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author jsie
 */

@Entity
@IdClass(BillPK.class)
@DiscriminatorColumn(length=31)
public abstract class Bill { 

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long reference;

    @Id
    @Temporal(TemporalType.DATE)
    private Date deliveyDate;

    @Basic
    private long amount;

    @Basic
    private int discount;

    @Basic
    private boolean paidoff;

    @Basic
    private String comment;

    @Id@ManyToOne(targetEntity = Professional.class)
    private Professional professional;

    @OneToMany(targetEntity = Payment.class,mappedBy = "bill")
    private List<Payment> payments;

    @ManyToMany(targetEntity = Offering.class)
    private List<Offering> offerings;


    public Long getReference() {
        return this.reference;
    }

    public void setReference(Long reference) {
        this.reference = reference;
    }

    public Date getDeliveyDate() {
        return this.deliveyDate;
    }

    public void setDeliveyDate(Date deliveyDate) {
        this.deliveyDate = deliveyDate;
    }

    public long getAmount() {
        return this.amount;
    }

    public void setAmount(long amount) {
        this.amount = amount;
    }

    public int getDiscount() {
        return this.discount;
    }

    public void setDiscount(int discount) {
        this.discount = discount;
    }

    public boolean isPaidoff() {
        return this.paidoff;
    }

    public void setPaidoff(boolean paidoff) {
        this.paidoff = paidoff;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Professional getProfessional() {
        return this.professional;
    }

    public void setProfessional(Professional professional) {
        this.professional = professional;
    }

    public List<Payment> getPayments() {
        return this.payments;
    }

    public void setPayments(List<Payment> payments) {
        this.payments = payments;
    }

    public List<Offering> getOfferings() {
        return this.offerings;
    }

    public void setOfferings(List<Offering> offerings) {
        this.offerings = offerings;
    }


}
