/**
 * This file was generated by the JPA Modeler
 */ 

package fr.trendev.comptandye.entity;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;

/**
 * @author jsie
 */

@Entity
public class ClientBill extends Bill { 

    @ManyToOne(targetEntity = Client.class)
    private Client client;


    public Client getClient() {
        return this.client;
    }

    public void setClient(Client client) {
        this.client = client;
    }


}
