/**
 * This file was generated by the JPA Modeler
 */ 

package fr.trendev.comptandye.entity;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;

/**
 * @author jsie
 */

@Entity
public class Individual extends Customer { 

    @OneToMany(targetEntity = InvidualBill.class,mappedBy = "individual")
    private List<InvidualBill> invidualBills;

    @ManyToMany(targetEntity = Professional.class)
    private List<Professional> professionals;


    public List<InvidualBill> getInvidualBills() {
        return this.invidualBills;
    }

    public void setInvidualBills(List<InvidualBill> invidualBills) {
        this.invidualBills = invidualBills;
    }

    public List<Professional> getProfessionals() {
        return this.professionals;
    }

    public void setProfessionals(List<Professional> professionals) {
        this.professionals = professionals;
    }


}
