/**
 * This file was generated by the JPA Modeler
 */ 

package fr.trendev.comptandye.entity;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;

/**
 * @author jsie
 */

@Entity
public class Individual extends Customer { 

    @ManyToMany(targetEntity = Professional.class,mappedBy = "individuals")
    private List<Professional> professionals;


    public List<Professional> getProfessionals() {
        return this.professionals;
    }

    public void setProfessionals(List<Professional> professionals) {
        this.professionals = professionals;
    }


}
