/**
 * This file was generated by the JPA Modeler
 */ 

package fr.trendev.comptandye.entity;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;

/**
 * @author jsie
 */

@Entity
public class InvidualBill extends Bill { 

    @ManyToOne(targetEntity = Individual.class)
    private Individual individual;


    public Individual getIndividual() {
        return this.individual;
    }

    public void setIndividual(Individual individual) {
        this.individual = individual;
    }


}
