/**
 * This file was generated by the JPA Modeler
 */ 

package fr.trendev.comptandye.entity;

import javax.persistence.Entity;

/**
 * @author jsie
 */

@Entity
public class Service extends Offering { 



}
