//
// This file was generated by the JPA Modeler
//
package fr.trendev.comptandye.entity;

import java.io.Serializable;
import javax.persistence.Embeddable;



@Embeddable
public class UserAccountPK implements Serializable {

    private String email;

    private String uuid;

    public UserAccountPK(){
    }

    public UserAccountPK(String email,String uuid){
        this.email=email;
        this.uuid=uuid;
    }


   public String getEmail() {
        return this.email;
    }

    public void setEmail (String email) {
        this.email = email;
    }

   public String getUuid() {
        return this.uuid;
    }

    public void setUuid (String uuid) {
        this.uuid = uuid;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {return false;}
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {return false;}
        final UserAccountPK other = (UserAccountPK) obj;
        if (!java.util.Objects.equals(this.getEmail(), other.getEmail())) {        return false;        }
        if (!java.util.Objects.equals(this.getUuid(), other.getUuid())) {        return false;        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + (this.getEmail() != null ? this.getEmail().hashCode() : 0);
        hash = 97 * hash + (this.getUuid() != null ? this.getUuid().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "UserAccountPK{" + " email=" + email + ", uuid=" + uuid + '}';
    }

}
