/**
 * This file was generated by the JPA Modeler
 */ 

package fr.trendev.comptandye.entity;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * @author jsie
 */

@Entity
@Table(name="USER_ACCOUNT")
@DiscriminatorColumn(length=31,name="ACCOUNT_TYPE")
public abstract class UserAccount { 

    @EmbeddedId
    private UserAccountPK userAccountEmbeddedId;

    @Basic
    private String password;

    @ManyToMany(targetEntity = UserGroup.class)
    private List<UserGroup> userGroups;


    public UserAccountPK getUserAccountEmbeddedId() {
        return this.userAccountEmbeddedId;
    }

    public void setUserAccountEmbeddedId(UserAccountPK userAccountEmbeddedId) {
        this.userAccountEmbeddedId = userAccountEmbeddedId;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<UserGroup> getUserGroups() {
        return this.userGroups;
    }

    public void setUserGroups(List<UserGroup> userGroups) {
        this.userGroups = userGroups;
    }


}
