/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.purchaseexpense.entities;

import fr.trendev.comptandye.expense.entities.Expense;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.purchaseditem.entities.PurchasedItem;
import fr.trendev.comptandye.utils.ExpenseType;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class PurchaseExpense extends Expense {

    @Basic
    @NotNull(
            message = "The invoice reference cannot be null in a Purchase (extending an Expense)")
    private String invoiceRef;

    @OneToMany(targetEntity = PurchasedItem.class, mappedBy = "purchaseExpense")
    @JsonIgnore
    private List<PurchasedItem> purchasedItems = new LinkedList<>();

    public PurchaseExpense() {
        this.cltype = ExpenseType.PURCHASE_EXPENSE;
    }

    public String getInvoiceRef() {
        return this.invoiceRef;
    }

    public void setInvoiceRef(String invoiceRef) {
        this.invoiceRef = invoiceRef;
    }

    public List<PurchasedItem> getPurchasedItems() {
        return this.purchasedItems;
    }

    public void setPurchasedItems(List<PurchasedItem> purchasedItems) {
        this.purchasedItems = purchasedItems;
    }

}