/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.purchasedoffering.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.offering.entities.Offering;
import java.math.BigDecimal;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class PurchasedOffering {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * Quantity
     */
    @Basic
    private int qty = 1;

    @Column(updatable = false, scale = 2, precision = 5)
    @Basic
    private BigDecimal vatRate;

    @Embedded
    private OfferingSnapshot offeringSnapshot = new OfferingSnapshot();

    @Embedded
    private OfferingExtents offeringExtents;

    @ManyToOne(targetEntity = Offering.class)
    private Offering offering;

    public PurchasedOffering() {
    }

    public PurchasedOffering(int qty, Offering offering) {
        this.qty = qty;
        this.offering = offering;
        this.offeringSnapshot = new OfferingSnapshot(offering);
        this.offeringExtents = new OfferingExtents(offering);

        /* Offering/PurchasedOffering links are set/destroyed in the rest api services */
        // this.offering.getPurchasedOfferings().add(this); */
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getQty() {
        return this.qty;
    }

    public void setQty(int qty) {
        this.qty = qty;
    }

    public BigDecimal getVatRate() {
        return this.vatRate;
    }

    public void setVatRate(BigDecimal vatRate) {
        this.vatRate = vatRate;
    }

    public OfferingSnapshot getOfferingSnapshot() {
        return this.offeringSnapshot;
    }

    public void setOfferingSnapshot(OfferingSnapshot offeringSnapshot) {
        this.offeringSnapshot = offeringSnapshot;
    }

    public OfferingExtents getOfferingExtents() {
        return this.offeringExtents;
    }

    public void setOfferingExtents(OfferingExtents offeringExtents) {
        this.offeringExtents = offeringExtents;
    }

    public Offering getOffering() {
        return this.offering;
    }

    public void setOffering(Offering offering) {
        this.offering = offering;
    }

}