//
// This file was generated by the JPA Modeler
//
package fr.trendev.comptandye.entities;

import java.io.Serializable;



public class CommentPK implements Serializable {

    private Long id;

    private Long customerDetails;

    public CommentPK(){
    }

    public CommentPK(Long id,Long customerDetails){
        this.id=id;
        this.customerDetails=customerDetails;
    }


   public Long getId() {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

   public Long getCustomerDetails() {
        return this.customerDetails;
    }

    public void setCustomerDetails (Long customerDetails) {
        this.customerDetails = customerDetails;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {return false;}
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {return false;}
        final CommentPK other = (CommentPK) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {        return false;        }
        if (!java.util.Objects.equals(this.getCustomerDetails(), other.getCustomerDetails())) {        return false;        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + (this.getId() != null ? this.getId().hashCode() : 0);
        hash = 37 * hash + (this.getCustomerDetails() != null ? this.getCustomerDetails().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "CommentPK{" + " id=" + id + ", customerDetails=" + customerDetails + '}';
    }

}
