/**
 * This file was generated by the JPA Modeler
 */ 

package fr.trendev.comptandye.entities;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

/**
 * @author jsie
 */

@Entity
public class Pro extends Person { 

    @OneToMany(targetEntity = Client.class)
    private List<Client> clients;


    public List<Client> getClients() {
        return this.clients;
    }

    public void setClients(List<Client> clients) {
        this.clients = clients;
    }


}
