//
// This file was generated by the JPA Modeler
//
package fr.trendev.comptandye.entities;

import java.io.Serializable;



public class UserDetailsPK implements Serializable {

    private Long id;

    private Long person;

    public UserDetailsPK(){
    }

    public UserDetailsPK(Long id,Long person){
        this.id=id;
        this.person=person;
    }


   public Long getId() {
        return this.id;
    }

    public void setId (Long id) {
        this.id = id;
    }

   public Long getPerson() {
        return this.person;
    }

    public void setPerson (Long person) {
        this.person = person;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {return false;}
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {return false;}
        final UserDetailsPK other = (UserDetailsPK) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {        return false;        }
        if (!java.util.Objects.equals(this.getPerson(), other.getPerson())) {        return false;        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 29 * hash + (this.getId() != null ? this.getId().hashCode() : 0);
        hash = 29 * hash + (this.getPerson() != null ? this.getPerson().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "UserDetailsPK{" + " id=" + id + ", person=" + person + '}';
    }

}
