/**
 * This file was generated by the JPA Modeler
 */ 

package fr.trendev.comptandye.entities;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * @author jsie
 */

@Entity
@Table(name="USER_ACCOUNT")
@DiscriminatorColumn(length=31,name="ACCOUNT_TYPE")
public abstract class UserAccount { 

    @Id
    private String email;

    @Basic
    private String password;

    @Basic
    private String uuid;

    @ManyToMany(targetEntity = UserGroup.class)
    private List<UserGroup> userGroups;


    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public List<UserGroup> getUserGroups() {
        return this.userGroups;
    }

    public void setUserGroups(List<UserGroup> userGroups) {
        this.userGroups = userGroups;
    }


}
