/**
 * This file was generated by the JPA Modeler
 */
package fr.trendev.comptandye.entities;

import javax.persistence.Entity;

/**
 * @author jsie
 */
@Entity
public class Administrator extends UserAccount {

    public Administrator(String email, String password, String username,
            String uuid) {
        super(email, password, username, uuid);
    }

    public Administrator() {
        super();
    }

}