/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author jsie
 */
@Entity
@IdClass(BillPK.class)
@DiscriminatorColumn(length = 31)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@SuppressWarnings("unchecked")
public abstract class Bill {

    /**
     * Will be automatically generated based on the deliveryDate, the
     * Professional email and a timestamp.
     */
    @Id
    private String reference;

    @Column(columnDefinition = "DATETIME(3) NOT NULL")
    @Id
    @Temporal(TemporalType.TIMESTAMP)
    private Date deliveryDate;

    /**
     * Amount in cents (1/100 of the currency)
     */
    @Basic
    private int amount;

    /**
     * a percentage discount
     */
    @Basic
    private int discount;

    @Column(columnDefinition = "DATETIME(3)")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date paymentDate;

    @ElementCollection
    private List<String> comments = new LinkedList<>();

    @Id
    @ManyToOne(cascade = {CascadeType.MERGE, CascadeType.PERSIST,
        CascadeType.REFRESH}, targetEntity = Professional.class)
    @JoinColumn(name = "PROFESSIONAL_EMAIL", referencedColumnName = "EMAIL")
    @JsonIgnore
    private Professional professional;

    /**
     * Should be ignored during a PUT
     */
    @OneToMany(cascade = {CascadeType.ALL}, targetEntity = Payment.class,
            orphanRemoval = true)
    private List<Payment> payments = new LinkedList<>();

    /**
     * Should be ignored during a PUT and cannot be used to create Offerings
     * during a POST (No PERSIST on the relation).
     */
    @ManyToMany(cascade = {CascadeType.MERGE, CascadeType.REFRESH,
        CascadeType.REMOVE}, targetEntity = Offering.class)
    private List<Offering> offerings = new LinkedList<>();

    public Bill(String reference, Date deliveryDate, int amount, int discount,
            Date paymentDate, List comments, Professional professional,
            List payments, List offerings) {
        this.reference = reference;
        this.deliveryDate = deliveryDate;
        this.amount = amount;
        this.discount = discount;
        this.paymentDate = paymentDate;
        this.comments = comments;
        this.professional = professional;
        this.payments = payments;
        this.offerings = offerings;
    }

    public Bill() {
    }

    public String getReference() {
        return this.reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public Date getDeliveryDate() {
        return this.deliveryDate;
    }

    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    public int getAmount() {
        return this.amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public int getDiscount() {
        return this.discount;
    }

    public void setDiscount(int discount) {
        this.discount = discount;
    }

    public Date getPaymentDate() {
        return this.paymentDate;
    }

    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    public List<String> getComments() {
        return this.comments;
    }

    public void setComments(List<String> comments) {
        this.comments = comments;
    }

    public Professional getProfessional() {
        return this.professional;
    }

    public void setProfessional(Professional professional) {
        this.professional = professional;
    }

    public List<Payment> getPayments() {
        return this.payments;
    }

    public void setPayments(List<Payment> payments) {
        this.payments = payments;
    }

    public List<Offering> getOfferings() {
        return this.offerings;
    }

    public void setOfferings(List<Offering> offerings) {
        this.offerings = offerings;
    }

}