//
// This file was generated by the Jeddict
//
package fr.trendev.comptandye.entities;

import java.io.Serializable;

public class ClientPK implements Serializable {

    private Long id;

    private String professionalFromClient;

    public ClientPK() {
    }

    public ClientPK(Long id, String professionalFromClient) {
        this.id = id;
        this.professionalFromClient = professionalFromClient;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProfessionalFromClient() {
        return this.professionalFromClient;
    }

    public void setProfessionalFromClient(String professionalFromClient) {
        this.professionalFromClient = professionalFromClient;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final ClientPK other = (ClientPK) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getProfessionalFromClient(), other.
                getProfessionalFromClient())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 23 * hash + (this.getId() != null ? this.getId().hashCode() : 0);
        hash = 23 * hash + (this.getProfessionalFromClient() != null ? this.
                getProfessionalFromClient().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "ClientPK{" + " id=" + id + ", professionalFromClient="
                + professionalFromClient + '}';
    }

}