/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.visitors.Visitor;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Individual extends Customer {

    @ManyToMany(targetEntity = Professional.class)
    @JsonIgnore
    private List<Professional> professionals = new LinkedList<>();

    public Individual(String email, String password, String username,
            String uuid) {
        super(email, password, username, uuid);
    }

    public Individual() {
        super();
    }

    public Individual(String email, String password, String username,
            String uuid, CustomerDetails customerDetails, Address address,
            SocialNetworkAccounts socialNetworkAccounts) {
        super(email, password, username, uuid, customerDetails, address,
                socialNetworkAccounts);
    }

    public List<Professional> getProfessionals() {
        return this.professionals;
    }

    public void setProfessionals(List<Professional> professionals) {
        this.professionals = professionals;
    }

    @Override
    public void accept(Visitor v) {
        v.visit(this);
    }

}