/**
 * This file was generated by the JPA Modeler
 */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;

/**
 * @author jsie
 */
@Entity
public class Individual extends Customer {

    @ManyToMany(targetEntity = Professional.class)
    @JsonIgnore
    private List<Professional> professionals;

    public Individual(String email, String password, String username,
            String uuid) {
        super(email, password, username, uuid);
    }

    public Individual() {
        super();
    }

    public List<Professional> getProfessionals() {
        return this.professionals;
    }

    public void setProfessionals(List<Professional> professionals) {
        this.professionals = professionals;
    }

}