/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.Date;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.OneToOne;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class IndividualBill extends Bill {

    public final String cltype = "individualbill";

    @OneToOne(targetEntity = Individual.class)
    @JsonIgnore
    private Individual individual;

    public IndividualBill(String reference, Date deliveryDate, int amount,
            int discount, Date paymentDate, List comments,
            Professional professional, List payments, List offerings,
            Individual individual) {
        super(reference, deliveryDate, amount, discount, paymentDate, comments,
                professional, payments, offerings);
        this.individual = individual;
    }

    public IndividualBill() {
    }

    public Individual getIndividual() {
        return this.individual;
    }

    public void setIndividual(Individual individual) {
        this.individual = individual;
    }

}