/**
 * This file was generated by the JPA Modeler
 */
package fr.trendev.comptandye.entities;

import javax.persistence.Entity;
import javax.persistence.OneToOne;

/**
 * @author jsie
 */
@Entity
public class InvidualBill extends Bill {

    @OneToOne(targetEntity = Individual.class)
    private Individual individual;

    public Individual getIndividual() {
        return this.individual;
    }

    public void setIndividual(Individual individual) {
        this.individual = individual;
    }

}