/**
 * This file was generated by the JPA Modeler
 */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * @author jsie
 */
@Entity
public class InvidualBill extends Bill {

    @OneToOne(targetEntity = CollectiveGroup.class)
    @JsonIgnore
    private CollectiveGroup collectiveGroup;

    @ManyToOne(targetEntity = Individual.class)
    @JsonIgnore
    private Individual individual;

    public CollectiveGroup getCollectiveGroup() {
        return this.collectiveGroup;
    }

    public void setCollectiveGroup(CollectiveGroup collectiveGroup) {
        this.collectiveGroup = collectiveGroup;
    }

    public Individual getIndividual() {
        return this.individual;
    }

    public void setIndividual(Individual individual) {
        this.individual = individual;
    }

}