/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import fr.trendev.comptandye.utils.NotificationLevelEnum;
import fr.trendev.comptandye.utils.NotificationType;
import fr.trendev.comptandye.utils.visitors.Visitor;
import javax.persistence.Basic;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

/**
 * @author jsie
 */
@Entity
@IdClass(NotificationPK.class)
@DiscriminatorColumn(length = 31)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "cltype",
        visible = true)
@JsonSubTypes({
    @JsonSubTypes.Type(value = ThresholdAlert.class,
            name = NotificationType.THRESHOLD_ALERT)})
public abstract class Notification {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    @NotNull(message = "cltype field in Notification cannot be null")
    protected String cltype;

    @Basic
    private boolean checked = false;

    @Basic
    @Enumerated(EnumType.STRING)
    private NotificationLevelEnum levelRank;

    @Id
    @ManyToOne(targetEntity = Professional.class)
    @JsonIgnore
    private Professional professional;

    public Notification() {
    }

    public Notification(NotificationLevelEnum levelRank,
            Professional professional) {
        this.levelRank = levelRank;
        this.professional = professional;
        this.professional.getNotifications().add(this);
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCltype() {
        return this.cltype;
    }

    public void setCltype(String cltype) {
        this.cltype = cltype;
    }

    public boolean isChecked() {
        return this.checked;
    }

    public void setChecked(boolean checked) {
        this.checked = checked;
    }

    public NotificationLevelEnum getLevelRank() {
        return this.levelRank;
    }

    public void setLevelRank(NotificationLevelEnum levelRank) {
        this.levelRank = levelRank;
    }

    public Professional getProfessional() {
        return this.professional;
    }

    public void setProfessional(Professional professional) {
        this.professional = professional;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}