/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import javax.persistence.Basic;
import javax.persistence.Embeddable;

/**
 * @author jsie
 */
@Embeddable
public class OfferingExtents {

    /**
     * Extent of the Services
     */
    @Basic
    private int services;

    /**
     * Extent of the Sales
     */
    @Basic
    private int sales;

    public OfferingExtents() {
    }

    public OfferingExtents(int services, int sales) {
        this.services = services;
        this.sales = sales;
    }

    public OfferingExtents(Offering offering) {
        //computes services/sales extents
    }

    public int getServices() {
        return this.services;
    }

    public void setServices(int services) {
        this.services = services;
    }

    public int getSales() {
        return this.sales;
    }

    public void setSales(int sales) {
        this.sales = sales;
    }

}