/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import javax.persistence.Basic;
import javax.persistence.Embeddable;

/**
 * @author jsie
 */
@Embeddable
public class OfferingSnapshot {

    @Basic
    private String cltype;

    @Basic
    private String name;

    /**
     * Price in cents (1/100 of the currency)
     */
    @Basic
    private int price;

    /**
     * Duration (in minutes)
     */
    @Basic
    private int duration;

    public String getCltype() {
        return this.cltype;
    }

    public void setCltype(String cltype) {
        this.cltype = cltype;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getPrice() {
        return this.price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public int getDuration() {
        return this.duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

}