//
// This file was generated by the Jeddict
//
package fr.trendev.comptandye.entities;

import java.io.Serializable;

public class OfferingPK implements Serializable {

    private Long id;

    private String professionalFromOffering;

    public OfferingPK() {
    }

    public OfferingPK(Long id, String professionalFromOffering) {
        this.id = id;
        this.professionalFromOffering = professionalFromOffering;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProfessionalFromOffering() {
        return this.professionalFromOffering;
    }

    public void setProfessionalFromOffering(String professionalFromOffering) {
        this.professionalFromOffering = professionalFromOffering;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final OfferingPK other = (OfferingPK) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getProfessionalFromOffering(), other.
                getProfessionalFromOffering())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 41 * hash + (this.getId() != null ? this.getId().hashCode() : 0);
        hash = 41 * hash + (this.getProfessionalFromOffering() != null ? this.
                getProfessionalFromOffering().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "OfferingPK{" + " id=" + id + ", professionalFromOffering="
                + professionalFromOffering + '}';
    }

}