/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.visitors.Visitor;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Pack extends Offering {

    /**
     * TODO : recursively check that all services and packs are owned by the
     * same Professional.
     */
    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.PERSIST,
        CascadeType.REFRESH}, targetEntity = Offering.class)
    @JoinTable(name = "PACK", joinColumns = {
        @JoinColumn(name = "PACK_ID", referencedColumnName = "OFFERING_ID",
                table = "OFFERING")
        ,@JoinColumn(name = "PACK_PROFESSIONAL_EMAIL",
                referencedColumnName = "OFFERING_PRO_EMAIL", table = "OFFERING")})
    private List<Offering> offerings = new LinkedList<>();

    public Pack(String name, int price, int duration, Professional professional) {
        super(name, price, duration, professional);
    }

    public Pack() {
    }

    public List<Offering> getOfferings() {
        return this.offerings;
    }

    public void setOfferings(List<Offering> offerings) {
        this.offerings = offerings;
    }

    @Override
    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}