/**
 * This file was generated by the JPA Modeler
 */
package fr.trendev.comptandye.entities;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;

/**
 * @author jsie
 */
@Entity
public class Package extends Offering {

    @OneToMany(targetEntity = Offering.class)
    @JoinTable(name = "PACKAGE_SERVICES")
    private List<Offering> offerings;

    public List<Offering> getOfferings() {
        return this.offerings;
    }

    public void setOfferings(List<Offering> offerings) {
        this.offerings = offerings;
    }

}