/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.visitors.Visitor;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class PaymentMode {

    @Id
    private String name;

    public PaymentMode(String name) {
        this.name = name;
    }

    public PaymentMode() {
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void accept(Visitor v) {
        v.visit(this);
    }

}