/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import fr.trendev.comptandye.utils.ProductRecordType;
import fr.trendev.comptandye.utils.visitors.Visitor;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * @author jsie
 */
@Entity
@DiscriminatorColumn(length = 31)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "cltype",
        visible = true)
@JsonSubTypes({
    @JsonSubTypes.Type(value = PurchasedItem.class,
            name = ProductRecordType.PURCHASED_ITEM)
    ,   @JsonSubTypes.Type(value = UsedItem.class,
            name = ProductRecordType.USED_ITEM)
    ,  @JsonSubTypes.Type(value = ReturnedItem.class,
            name = ProductRecordType.RETURNED_ITEM)
    ,  @JsonSubTypes.Type(value = SoldItem.class,
            name = ProductRecordType.SOLD_ITEM)})
public abstract class ProductRecord {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    @NotNull(message = "cltype field in ProductRecord cannot be null")
    protected String cltype;

    @Column(columnDefinition = "DATETIME(3)")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    @NotNull(message = "recordDate field in ProductRecard cannot be null")
    private Date recordDate = new Date();

    @Basic
    private int qty;

    @ManyToOne(targetEntity = Product.class)
    private Product product;

    public ProductRecord(String cltype, Date recordDate, int qty) {
        this.cltype = cltype;
        this.recordDate = recordDate;
        this.qty = qty;
    }

    public ProductRecord() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCltype() {
        return this.cltype;
    }

    public void setCltype(String cltype) {
        this.cltype = cltype;
    }

    public Date getRecordDate() {
        return this.recordDate;
    }

    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    public int getQty() {
        return this.qty;
    }

    public void setQty(int qty) {
        this.qty = qty;
    }

    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}