/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

/**
 * @author jsie
 */
@Entity
public class Purchase extends Expense {

    @Basic
    @NotNull(
            message = "The invoice reference cannot be null in a Purchase (extending an Expense)")
    private String invoiceRef;

    @OneToMany(targetEntity = PurchasedItem.class, mappedBy = "purchase")
    @JsonIgnore
    private List<PurchasedItem> purchasedItems = new LinkedList<>();

    public String getInvoiceRef() {
        return this.invoiceRef;
    }

    public void setInvoiceRef(String invoiceRef) {
        this.invoiceRef = invoiceRef;
    }

    public List<PurchasedItem> getPurchasedItems() {
        return this.purchasedItems;
    }

    public void setPurchasedItems(List<PurchasedItem> purchasedItems) {
        this.purchasedItems = purchasedItems;
    }

}