/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import javax.persistence.Basic;
import javax.persistence.Entity;

/**
 * @author jsie
 */
@Entity
public class Purchase extends Expense {

    @Basic
    private String invoiceRef;

    public String getInvoiceRef() {
        return this.invoiceRef;
    }

    public void setInvoiceRef(String invoiceRef) {
        this.invoiceRef = invoiceRef;
    }

}