/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.math.BigDecimal;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class PurchasedOffering {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * Quantity
     */
    @Basic
    private int qty = 1;

    @Column(updatable = false, scale = 2, precision = 5)
    @Basic
    private BigDecimal vatRate;

    /**
     * Extent of the Services
     */
    @Basic
    private int extentServices;

    /**
     * Extent of the Sales
     */
    @Basic
    private int extentSales;

    @Embedded
    private OfferingSnapshot offeringSnapshot = new OfferingSnapshot();

    @ManyToOne(targetEntity = Offering.class)
    private Offering offering;

    public PurchasedOffering() {
    }

    public PurchasedOffering(int qty, Offering offering) {
        this.qty = qty;
        this.offering = offering;
        this.offeringSnapshot = new OfferingSnapshot(offering);
// this.offering.getPurchasedOfferings().add(this);
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getQty() {
        return this.qty;
    }

    public void setQty(int qty) {
        this.qty = qty;
    }

    public BigDecimal getVatRate() {
        return this.vatRate;
    }

    public void setVatRate(BigDecimal vatRate) {
        this.vatRate = vatRate;
    }

    public int getExtentServices() {
        return this.extentServices;
    }

    public void setExtentServices(int extentServices) {
        this.extentServices = extentServices;
    }

    public int getExtentSales() {
        return this.extentSales;
    }

    public void setExtentSales(int extentSales) {
        this.extentSales = extentSales;
    }

    public OfferingSnapshot getOfferingSnapshot() {
        return this.offeringSnapshot;
    }

    public void setOfferingSnapshot(OfferingSnapshot offeringSnapshot) {
        this.offeringSnapshot = offeringSnapshot;
    }

    public Offering getOffering() {
        return this.offering;
    }

    public void setOffering(Offering offering) {
        this.offering = offering;
    }

}