/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.validation.constraints.NotNull;

/**
 * @author jsie
 */
@Entity
public class Purchase extends Expense {

    @Basic
    @NotNull(
            message = "The invoice reference cannot be null in a Purchase (extending an Expense)")
    private String invoiceRef;

    public String getInvoiceRef() {
        return this.invoiceRef;
    }

    public void setInvoiceRef(String invoiceRef) {
        this.invoiceRef = invoiceRef;
    }

}