/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.utils.OfferingType;
import fr.trendev.comptandye.utils.visitors.Visitor;
import javax.persistence.Entity;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Service extends Offering {

    public Service(String name, int price, int duration,
            Professional professional) {
        super(name, price, duration, professional);
        this.cltype = OfferingType.SERVICE;
    }

    public Service() {
        this.cltype = OfferingType.SERVICE;
    }

    @Override
    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}