/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.utils.ProductRecordType;
import fr.trendev.comptandye.utils.visitors.Visitor;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToOne;

/**
 * Record added when an item is sold and linked with an active Bill
 *
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class SoldItem extends ProductRecord {

    @OneToOne(targetEntity = Bill.class)
    @JoinTable(name = "SOLD_ITEM", joinColumns = {
        @JoinColumn(name = "ID", referencedColumnName = "ID",
                table = "PRODUCTRECORD")})
    private Bill bill;

    public SoldItem() {
        super();
        this.cltype = ProductRecordType.SOLD_ITEM;
    }

    public Bill getBill() {
        return this.bill;
    }

    public void setBill(Bill bill) {
        this.bill = bill;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}