/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.utils.ProductRecordType;
import javax.persistence.Entity;

/**
 * Record added when an Item is consumed during the delivery
 *
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class UsedItem extends ProductRecord {

    public UsedItem() {
        super();
        this.cltype = ProductRecordType.USED_ITEM;
    }

}