/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class VatRates {

    /**
     * the country's id (ex: France -> FR)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String countryId;

    @Basic
    private String country;

    @Column(scale = 2, precision = 5)
    @ElementCollection
    private List<BigDecimal> rates = new ArrayList<>();

    public String getCountryId() {
        return this.countryId;
    }

    public void setCountryId(String countryId) {
        this.countryId = countryId;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public List<BigDecimal> getRates() {
        return this.rates;
    }

    public void setRates(List<BigDecimal> rates) {
        this.rates = rates;
    }

}