/** * This file was generated by the JPA Modeler */
package fr.trendev.kiam.purchasedoffering.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.kiam.business.entities.Business;
import fr.trendev.kiam.offering.entities.Offering;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Embeddable;
import javax.persistence.OneToMany;

/**
 * @author jsie
 */
@Embeddable
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class OfferingSnapshot {

    @Basic
    private String cltype;

    @Basic
    private String name;

    @Basic
    private String shortname;

    @Basic
    private int price;

    @Basic
    private int duration;

    @OneToMany
    private List<Business> businesses = new LinkedList<>();

    public OfferingSnapshot() {
    }

    public OfferingSnapshot(Offering offering) {
        this.cltype = offering.getCltype();
        this.name = offering.getName();
        this.shortname = offering.getShortname();
        this.price = offering.getPrice();
        this.duration = offering.getDuration();
        this.businesses = offering.getBusinesses();
    }

    public String getCltype() {
        return cltype;
    }

    public void setCltype(String cltype) {
        this.cltype = cltype;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getShortname() {
        return shortname;
    }

    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    public int getPrice() {
        return price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public int getDuration() {
        return duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

    public List<Business> getBusinesses() {
        return businesses;
    }

    public void setBusinesses(List<Business> businesses) {
        this.businesses = businesses;
    }

}