/** * This file was generated by the JPA Modeler */
package fr.trendev.comptandye.payment.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import fr.trendev.comptandye.paymentmode.entities.PaymentMode;
import fr.trendev.comptandye.utils.Visitor;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;

/**
 * @author jsie
 */
@Entity
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Payment {

    @Id
    @NotNull(message = "Payment ID cannot be null")
    private String id;

    @Basic
    private int amount;

    @OneToOne(optional = false)
    private PaymentMode paymentMode;

    public Payment(int amount, PaymentMode paymentMode) {
        this.amount = amount;
        this.paymentMode = paymentMode;
    }

    public Payment() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public PaymentMode getPaymentMode() {
        return paymentMode;
    }

    public void setPaymentMode(PaymentMode paymentMode) {
        this.paymentMode = paymentMode;
    }

    public <T> T accept(Visitor<T> v) {
        return v.visit(this);
    }

}