version: '3'
services:
  web-payara:
    build: .
    ports:
      - "8080:8080"
      - "8181:8181"
      - "4848:4848"
    depends_on:
      - "db-mysql"
  db-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=7gXf1pwmtW
      - MYSQL_USER=admin_comptandye_20170328
      - MYSQL_PASSWORD=SfBuVPRw0S
      - MYSQL_DATABASE=comptandye_master
    volumes:
      - $HOME/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
